name: "uploadtoS3"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Upload to Amazon S3"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test Srini account
        uses: aws-actions/configure-aws-credentials@e21f7333e801ca751f058cc52de17f0ee6e1da6f
        with:
          role-to-assume: arn:aws:iam::595123332338:role/AssumRoleTest
          aws-region: us-east-1
    
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://assume-role-github-actions-test
